# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5af6219be6e2bf738eef11422c38185ab4aa6ba5567c22b8f7b4f48799c99c6902edcae917d627ed9605f2edfcb195894c93bc88faac6427b40cd4fafb30d32c

test:
  secret_key_base: 1f3445f4762cf3e4b9642fe1f160761aaeb6b7bd7b5020855bd1af5914ea032d40c588b9cf76e9e1f99c913b1612207203eb1a6d22bc99f3661b0f622090a0c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
